# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/config/six_step/log_item.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.503474 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.six_step.log_item
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import voltbro.config.six_step

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class log_item_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 is_on:           None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 is_stalling:     None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 target_speed:    None | uavcan.primitive.scalar.Real32_1_0 = None,
                 speed:           None | uavcan.primitive.scalar.Real32_1_0 = None,
                 elec_theta:      None | uavcan.primitive.scalar.Real32_1_0 = None,
                 PWM:             None | uavcan.primitive.scalar.Integer32_1_0 = None,
                 I_A:             None | uavcan.primitive.scalar.Real32_1_0 = None,
                 I_B:             None | uavcan.primitive.scalar.Real32_1_0 = None,
                 I_C:             None | uavcan.primitive.scalar.Real32_1_0 = None,
                 velocity_report: None | voltbro.config.six_step.pid_report_1_0 = None,
                 current_report:  None | voltbro.config.six_step.pid_report_1_0 = None) -> None:
        """
        voltbro.config.six_step.log_item.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param is_on:           uavcan.primitive.scalar.Integer8.1.0 is_on
        :param is_stalling:     uavcan.primitive.scalar.Integer8.1.0 is_stalling
        :param target_speed:    uavcan.primitive.scalar.Real32.1.0 target_speed
        :param speed:           uavcan.primitive.scalar.Real32.1.0 speed
        :param elec_theta:      uavcan.primitive.scalar.Real32.1.0 elec_theta
        :param PWM:             uavcan.primitive.scalar.Integer32.1.0 PWM
        :param I_A:             uavcan.primitive.scalar.Real32.1.0 I_A
        :param I_B:             uavcan.primitive.scalar.Real32.1.0 I_B
        :param I_C:             uavcan.primitive.scalar.Real32.1.0 I_C
        :param velocity_report: voltbro.config.six_step.pid_report.1.0 velocity_report
        :param current_report:  voltbro.config.six_step.pid_report.1.0 current_report
        """
        self._is_on:           uavcan.primitive.scalar.Integer8_1_0
        self._is_stalling:     uavcan.primitive.scalar.Integer8_1_0
        self._target_speed:    uavcan.primitive.scalar.Real32_1_0
        self._speed:           uavcan.primitive.scalar.Real32_1_0
        self._elec_theta:      uavcan.primitive.scalar.Real32_1_0
        self._PWM:             uavcan.primitive.scalar.Integer32_1_0
        self._I_A:             uavcan.primitive.scalar.Real32_1_0
        self._I_B:             uavcan.primitive.scalar.Real32_1_0
        self._I_C:             uavcan.primitive.scalar.Real32_1_0
        self._velocity_report: voltbro.config.six_step.pid_report_1_0
        self._current_report:  voltbro.config.six_step.pid_report_1_0

        if is_on is None:
            self.is_on = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(is_on, uavcan.primitive.scalar.Integer8_1_0):
            self.is_on = is_on
        else:
            raise ValueError(f'is_on: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(is_on).__name__}')

        if is_stalling is None:
            self.is_stalling = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(is_stalling, uavcan.primitive.scalar.Integer8_1_0):
            self.is_stalling = is_stalling
        else:
            raise ValueError(f'is_stalling: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(is_stalling).__name__}')

        if target_speed is None:
            self.target_speed = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(target_speed, uavcan.primitive.scalar.Real32_1_0):
            self.target_speed = target_speed
        else:
            raise ValueError(f'target_speed: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(target_speed).__name__}')

        if speed is None:
            self.speed = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(speed, uavcan.primitive.scalar.Real32_1_0):
            self.speed = speed
        else:
            raise ValueError(f'speed: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(speed).__name__}')

        if elec_theta is None:
            self.elec_theta = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(elec_theta, uavcan.primitive.scalar.Real32_1_0):
            self.elec_theta = elec_theta
        else:
            raise ValueError(f'elec_theta: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(elec_theta).__name__}')

        if PWM is None:
            self.PWM = uavcan.primitive.scalar.Integer32_1_0()
        elif isinstance(PWM, uavcan.primitive.scalar.Integer32_1_0):
            self.PWM = PWM
        else:
            raise ValueError(f'PWM: expected uavcan.primitive.scalar.Integer32_1_0 '
                             f'got {type(PWM).__name__}')

        if I_A is None:
            self.I_A = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(I_A, uavcan.primitive.scalar.Real32_1_0):
            self.I_A = I_A
        else:
            raise ValueError(f'I_A: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(I_A).__name__}')

        if I_B is None:
            self.I_B = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(I_B, uavcan.primitive.scalar.Real32_1_0):
            self.I_B = I_B
        else:
            raise ValueError(f'I_B: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(I_B).__name__}')

        if I_C is None:
            self.I_C = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(I_C, uavcan.primitive.scalar.Real32_1_0):
            self.I_C = I_C
        else:
            raise ValueError(f'I_C: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(I_C).__name__}')

        if velocity_report is None:
            self.velocity_report = voltbro.config.six_step.pid_report_1_0()
        elif isinstance(velocity_report, voltbro.config.six_step.pid_report_1_0):
            self.velocity_report = velocity_report
        else:
            raise ValueError(f'velocity_report: expected voltbro.config.six_step.pid_report_1_0 '
                             f'got {type(velocity_report).__name__}')

        if current_report is None:
            self.current_report = voltbro.config.six_step.pid_report_1_0()
        elif isinstance(current_report, voltbro.config.six_step.pid_report_1_0):
            self.current_report = current_report
        else:
            raise ValueError(f'current_report: expected voltbro.config.six_step.pid_report_1_0 '
                             f'got {type(current_report).__name__}')

    @property
    def is_on(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 is_on
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._is_on

    @is_on.setter
    def is_on(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._is_on = x
        else:
            raise ValueError(f'is_on: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def is_stalling(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 is_stalling
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._is_stalling

    @is_stalling.setter
    def is_stalling(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._is_stalling = x
        else:
            raise ValueError(f'is_stalling: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def target_speed(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 target_speed
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._target_speed

    @target_speed.setter
    def target_speed(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._target_speed = x
        else:
            raise ValueError(f'target_speed: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def speed(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 speed
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._speed

    @speed.setter
    def speed(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._speed = x
        else:
            raise ValueError(f'speed: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def elec_theta(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 elec_theta
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._elec_theta

    @elec_theta.setter
    def elec_theta(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._elec_theta = x
        else:
            raise ValueError(f'elec_theta: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def PWM(self) -> uavcan.primitive.scalar.Integer32_1_0:
        """
        uavcan.primitive.scalar.Integer32.1.0 PWM
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._PWM

    @PWM.setter
    def PWM(self, x: uavcan.primitive.scalar.Integer32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer32_1_0):
            self._PWM = x
        else:
            raise ValueError(f'PWM: expected uavcan.primitive.scalar.Integer32_1_0 got {type(x).__name__}')

    @property
    def I_A(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 I_A
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._I_A

    @I_A.setter
    def I_A(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._I_A = x
        else:
            raise ValueError(f'I_A: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def I_B(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 I_B
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._I_B

    @I_B.setter
    def I_B(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._I_B = x
        else:
            raise ValueError(f'I_B: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def I_C(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 I_C
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._I_C

    @I_C.setter
    def I_C(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._I_C = x
        else:
            raise ValueError(f'I_C: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def velocity_report(self) -> voltbro.config.six_step.pid_report_1_0:
        """
        voltbro.config.six_step.pid_report.1.0 velocity_report
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity_report

    @velocity_report.setter
    def velocity_report(self, x: voltbro.config.six_step.pid_report_1_0) -> None:
        if isinstance(x, voltbro.config.six_step.pid_report_1_0):
            self._velocity_report = x
        else:
            raise ValueError(f'velocity_report: expected voltbro.config.six_step.pid_report_1_0 got {type(x).__name__}')

    @property
    def current_report(self) -> voltbro.config.six_step.pid_report_1_0:
        """
        voltbro.config.six_step.pid_report.1.0 current_report
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._current_report

    @current_report.setter
    def current_report(self, x: voltbro.config.six_step.pid_report_1_0) -> None:
        if isinstance(x, voltbro.config.six_step.pid_report_1_0):
            self._current_report = x
        else:
            raise ValueError(f'current_report: expected voltbro.config.six_step.pid_report_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.is_on._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.is_stalling._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.target_speed._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.speed._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.elec_theta._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.PWM._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.I_A._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.I_B._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.I_C._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of voltbro.config.six_step.pid_report.1.0, fixed bit length 128 (16 bytes)
        _ser_.add_aligned_u32(16)  # Delimiter header is constant in this case.
        _ser_base_offset_ = _ser_.current_bit_length
        self.velocity_report._serialize_(_ser_)
        assert _ser_.current_bit_length - _ser_base_offset_ == 128
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of voltbro.config.six_step.pid_report.1.0, fixed bit length 128 (16 bytes)
        _ser_.add_aligned_u32(16)  # Delimiter header is constant in this case.
        _ser_base_offset_ = _ser_.current_bit_length
        self.current_report._serialize_(_ser_)
        assert _ser_.current_bit_length - _ser_base_offset_ == 128
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 304 <= (_ser_.current_bit_length - _base_offset_) <= 560, \
            'Bad serialization of voltbro.config.six_step.log_item.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> log_item_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "is_on"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "is_stalling"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "target_speed"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "speed"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "elec_theta"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "PWM"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.primitive.scalar.Integer32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "I_A"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f7_ holds the value of "I_B"
        _des_.pad_to_alignment(8)
        _f7_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f8_ holds the value of "I_C"
        _des_.pad_to_alignment(8)
        _f8_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f9_ holds the value of "velocity_report"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of voltbro.config.six_step.pid_report.1.0, extent 128
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f9_ = voltbro.config.six_step.pid_report_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f10_ holds the value of "current_report"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of voltbro.config.six_step.pid_report.1.0, extent 128
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f10_ = voltbro.config.six_step.pid_report_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = log_item_1_0(
            is_on=_f0_,
            is_stalling=_f1_,
            target_speed=_f2_,
            speed=_f3_,
            elec_theta=_f4_,
            PWM=_f5_,
            I_A=_f6_,
            I_B=_f7_,
            I_C=_f8_,
            velocity_report=_f9_,
            current_report=_f10_)
        _des_.pad_to_alignment(8)
        assert 304 <= (_des_.consumed_bit_length - _base_offset_) <= 560, \
            'Bad deserialization of voltbro.config.six_step.log_item.1.0'
        assert isinstance(self, log_item_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'is_on=%s' % self.is_on,
            'is_stalling=%s' % self.is_stalling,
            'target_speed=%s' % self.target_speed,
            'speed=%s' % self.speed,
            'elec_theta=%s' % self.elec_theta,
            'PWM=%s' % self.PWM,
            'I_A=%s' % self.I_A,
            'I_B=%s' % self.I_B,
            'I_C=%s' % self.I_C,
            'velocity_report=%s' % self.velocity_report,
            'current_report=%s' % self.current_report,
        ])
        return f'voltbro.config.six_step.log_item.1.0({_o_0_})'

    _EXTENT_BYTES_ = 70

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8iT%E40{`t-OKjX!6rIU;lJt|%A0LTMK`QCbP0}_g<rkVZQZ*!<CM~Ui>hWy9%=Oe`8~Zs;Dpg8_sM^XB5j7hSRavq?>K=Af'
        'ASw`*5UN<QV&6p<EU3bLw&&}aN%{eVgrylj-+O)Ed-t4s@AE?2$6v2c1edqjnpYiFmx#k`jq2JtD(g%lidnEsN8`-*Rv%)zR=}Zp'
        'eBNUIRe#$B|GeMtbr8)knC(NtTRqKfSK+SBs!iI7K?~?2J!|S*woOSfjTtQ`Iocd?II|?(%n|fl@Vyk7WwxW4hVa+<W;DL)XOfx3'
        'MgM~D^$^Ort;sHDj(-}RH&}Ve%J<sGHKwcO<#ZF3a!R;ZBXovB==RbsomHqIS+>}wHp?VOp*pptBL-(VX7Bf56|5;P1o}?<upxT+'
        '$wsRv`SQKKX)R|kHF8!RpdKP?oaoHRaqu%KT%kf8P70=qE8OC3%og2<*Q7DjO$Zf+CGmkj<$LQfjMPx6tyVg^<jT0M_F1aCIDZ>a'
        'O~v;TzAIC2T}2d$JRjn7-iKYV*}>JQ%(9t65o`alw}#AUb4(?cX>+2f{-oDO9MiQGh6<e#i{e~fr?}~w?0a2VWXxPvNU!4FlDlzk'
        'Fa`b{h&{sVdo5=jghc>=_h&3u)-{FLEa&QC&N4ix?Fdmpw-vGM2$8{{7O{~Ar2$DG;Byg>bp)t`E3=uw1thbY!u-o1!EUcN*lfsb'
        '1JxmmnopA|QGj`yf(;XH65BL+;LNcox`&Z|*bgtl0eA^shF9R#U?put)^QtKi~K0#gX`k8&%U?npvK<_o~Q9KVu;sDObhd;krQXW'
        'Ae$IN-1r15n8-ekX>-(KHsz*WnX3wDm<n*hTbre-su{VM5xga|ldg_CpRd)ThmcMm`u&;Iq9bF%TA?H4tt;bp3z{J)i~~9+2AzV&'
        '2&{O!o3J^H8bMA^y0RmO4AmSW5+2dP=Tc6=Q>g1f9dcXO#SAfva`HagD0!zC)%OfFNnOmZu5sO@yecJOYbFgZzz*1X30Ga9IYZ+v'
        'rkvL`V^c*$7eP&pM`L{LN?)S#T3T94WRe$=0hLJzk~e&K4&Tw|)3(Sl2MH)DMOq69<{U`By=!oIWMpJ$aCm2WM{#&sWGxI}hQ1GH'
        '9T>U{dnRFTjB)T9jCyOsEmvm*917SEhnFXNM-(y!nYxsQNjMe+368_b5@+5ijouBFil9guDFRF|17<LwIs5_Y@@4Q>acbunCaJ}+'
        '+QblkPXw=tuAAvhAsiT|&FHaZncCi*A<xG+Q4Ok?Hbm!3_+lA!o+!=u&;WIn7yZv*)S5jxQ9t~xN6709H3u7N#^RcmXw+VT+H;N0'
        '3znv0yATa223!AwmxtlK&A>lb0)I3DAI`(Vl?#b~>-u9Uxayaef#u7~(Dv>7_F!!Z?&ZSrJN&ki!ZN(~(FzL&`*DzVw34)=NZQd_'
        '(yj^iY*U>u+r|zSW8AN3)ZyTvjOvk+i9qzjpKu43;J#Zo8eV5aO59IKOY8$hVq*U-Q?p5&n)~Rkpm%Mo^2uZ(v65h&tmx(&#!N$;'
        '=8U?>0<SAP72sJ(9EIw7yVoGraF01cx`5J!vb1PiEe?T!pE22f2~+hB++Rt|gH7jK#9yoUYb(a!F~=0oDr^qJ#Qn^Iw-Hal;RlaR'
        'fKe51;TOXeZ`}#QX?U2Ay2Q3jQXI|0UQrLL{3e_=c*sAEBN2{RRjvea(-bvwY>HWoYmH8KXTn2QZ%wj@gIa(`qKHQ(CFF@kCjchI'
        'P?Y}bab=WFYiF5mDjJ_J72eu>`bi|6;@ZKPyUHlS_zY|W19bQVO!y2wh3jw)zJbr-Teu0|!*}ol+{#a4DB#EZF#+>Y{96$ryuRWG'
        '<U{9Ns`Lr^=owcB+5heT`}U_wWi5r7k}6lbQ(^w}qO><&18c+|g~kIY9f%v(h$G`HO0#j}8gXQ7q11{S*NDFgjTce67&opFN1kt>'
        '^hVscMjRR6M(ORiag8`KzKhbkapP)nem{Z}*iZB(Avdv@jJ*+4RJ=1FR0A#XcWM<;o9e+f)f={{jaalyELhjDSlz@zbqgz$C{BNO'
        'UCU2Dc%xfEA<IiRz#Zpzi#Z01<c~U6exF$C<7r#@v6A!rI1V%8O*&JAL4(#bk!`8po20)0Z$mnM#}ohn'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
