# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-08 16:00:09.384721 UTC
# Namespace:     voltbro.battery

from voltbro.battery.buttons_1_0 import buttons_1_0 as buttons_1_0
from voltbro.battery.state_1_0 import state_1_0 as state_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
buttons_1 = buttons_1_0
state_1 = state_1_0
