# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/battery/state.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.489294 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.battery.state
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive
import uavcan.primitive.scalar
import uavcan.si.unit.electric_charge
import uavcan.si.unit.electric_current
import uavcan.si.unit.voltage

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class state_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 voltage:                 None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 current:                 None | uavcan.si.unit.electric_current.Scalar_1_0 = None,
                 charge:                  None | uavcan.si.unit.electric_charge.Scalar_1_0 = None,
                 capacity:                None | uavcan.si.unit.electric_charge.Scalar_1_0 = None,
                 design_capacity:         None | uavcan.si.unit.electric_charge.Scalar_1_0 = None,
                 power_supply_status:     None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 power_supply_health:     None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 power_supply_technology: None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 is_present:              None | uavcan.primitive.scalar.Integer8_1_0 = None,
                 location:                None | uavcan.primitive.String_1_0 = None,
                 serial_number:           None | uavcan.primitive.String_1_0 = None) -> None:
        """
        voltbro.battery.state.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param voltage:                 uavcan.si.unit.voltage.Scalar.1.0 voltage
        :param current:                 uavcan.si.unit.electric_current.Scalar.1.0 current
        :param charge:                  uavcan.si.unit.electric_charge.Scalar.1.0 charge
        :param capacity:                uavcan.si.unit.electric_charge.Scalar.1.0 capacity
        :param design_capacity:         uavcan.si.unit.electric_charge.Scalar.1.0 design_capacity
        :param power_supply_status:     uavcan.primitive.scalar.Integer8.1.0 power_supply_status
        :param power_supply_health:     uavcan.primitive.scalar.Integer8.1.0 power_supply_health
        :param power_supply_technology: uavcan.primitive.scalar.Integer8.1.0 power_supply_technology
        :param is_present:              uavcan.primitive.scalar.Integer8.1.0 is_present
        :param location:                uavcan.primitive.String.1.0 location
        :param serial_number:           uavcan.primitive.String.1.0 serial_number
        """
        self._voltage:                 uavcan.si.unit.voltage.Scalar_1_0
        self._current:                 uavcan.si.unit.electric_current.Scalar_1_0
        self._charge:                  uavcan.si.unit.electric_charge.Scalar_1_0
        self._capacity:                uavcan.si.unit.electric_charge.Scalar_1_0
        self._design_capacity:         uavcan.si.unit.electric_charge.Scalar_1_0
        self._power_supply_status:     uavcan.primitive.scalar.Integer8_1_0
        self._power_supply_health:     uavcan.primitive.scalar.Integer8_1_0
        self._power_supply_technology: uavcan.primitive.scalar.Integer8_1_0
        self._is_present:              uavcan.primitive.scalar.Integer8_1_0
        self._location:                uavcan.primitive.String_1_0
        self._serial_number:           uavcan.primitive.String_1_0

        if voltage is None:
            self.voltage = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(voltage, uavcan.si.unit.voltage.Scalar_1_0):
            self.voltage = voltage
        else:
            raise ValueError(f'voltage: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(voltage).__name__}')

        if current is None:
            self.current = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(current, uavcan.si.unit.electric_current.Scalar_1_0):
            self.current = current
        else:
            raise ValueError(f'current: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(current).__name__}')

        if charge is None:
            self.charge = uavcan.si.unit.electric_charge.Scalar_1_0()
        elif isinstance(charge, uavcan.si.unit.electric_charge.Scalar_1_0):
            self.charge = charge
        else:
            raise ValueError(f'charge: expected uavcan.si.unit.electric_charge.Scalar_1_0 '
                             f'got {type(charge).__name__}')

        if capacity is None:
            self.capacity = uavcan.si.unit.electric_charge.Scalar_1_0()
        elif isinstance(capacity, uavcan.si.unit.electric_charge.Scalar_1_0):
            self.capacity = capacity
        else:
            raise ValueError(f'capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 '
                             f'got {type(capacity).__name__}')

        if design_capacity is None:
            self.design_capacity = uavcan.si.unit.electric_charge.Scalar_1_0()
        elif isinstance(design_capacity, uavcan.si.unit.electric_charge.Scalar_1_0):
            self.design_capacity = design_capacity
        else:
            raise ValueError(f'design_capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 '
                             f'got {type(design_capacity).__name__}')

        if power_supply_status is None:
            self.power_supply_status = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(power_supply_status, uavcan.primitive.scalar.Integer8_1_0):
            self.power_supply_status = power_supply_status
        else:
            raise ValueError(f'power_supply_status: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(power_supply_status).__name__}')

        if power_supply_health is None:
            self.power_supply_health = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(power_supply_health, uavcan.primitive.scalar.Integer8_1_0):
            self.power_supply_health = power_supply_health
        else:
            raise ValueError(f'power_supply_health: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(power_supply_health).__name__}')

        if power_supply_technology is None:
            self.power_supply_technology = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(power_supply_technology, uavcan.primitive.scalar.Integer8_1_0):
            self.power_supply_technology = power_supply_technology
        else:
            raise ValueError(f'power_supply_technology: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(power_supply_technology).__name__}')

        if is_present is None:
            self.is_present = uavcan.primitive.scalar.Integer8_1_0()
        elif isinstance(is_present, uavcan.primitive.scalar.Integer8_1_0):
            self.is_present = is_present
        else:
            raise ValueError(f'is_present: expected uavcan.primitive.scalar.Integer8_1_0 '
                             f'got {type(is_present).__name__}')

        if location is None:
            self.location = uavcan.primitive.String_1_0()
        elif isinstance(location, uavcan.primitive.String_1_0):
            self.location = location
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 '
                             f'got {type(location).__name__}')

        if serial_number is None:
            self.serial_number = uavcan.primitive.String_1_0()
        elif isinstance(serial_number, uavcan.primitive.String_1_0):
            self.serial_number = serial_number
        else:
            raise ValueError(f'serial_number: expected uavcan.primitive.String_1_0 '
                             f'got {type(serial_number).__name__}')

    @property
    def voltage(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._voltage

    @voltage.setter
    def voltage(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._voltage = x
        else:
            raise ValueError(f'voltage: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def current(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 current
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._current

    @current.setter
    def current(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._current = x
        else:
            raise ValueError(f'current: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def charge(self) -> uavcan.si.unit.electric_charge.Scalar_1_0:
        """
        uavcan.si.unit.electric_charge.Scalar.1.0 charge
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._charge

    @charge.setter
    def charge(self, x: uavcan.si.unit.electric_charge.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_charge.Scalar_1_0):
            self._charge = x
        else:
            raise ValueError(f'charge: expected uavcan.si.unit.electric_charge.Scalar_1_0 got {type(x).__name__}')

    @property
    def capacity(self) -> uavcan.si.unit.electric_charge.Scalar_1_0:
        """
        uavcan.si.unit.electric_charge.Scalar.1.0 capacity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._capacity

    @capacity.setter
    def capacity(self, x: uavcan.si.unit.electric_charge.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_charge.Scalar_1_0):
            self._capacity = x
        else:
            raise ValueError(f'capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 got {type(x).__name__}')

    @property
    def design_capacity(self) -> uavcan.si.unit.electric_charge.Scalar_1_0:
        """
        uavcan.si.unit.electric_charge.Scalar.1.0 design_capacity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._design_capacity

    @design_capacity.setter
    def design_capacity(self, x: uavcan.si.unit.electric_charge.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_charge.Scalar_1_0):
            self._design_capacity = x
        else:
            raise ValueError(f'design_capacity: expected uavcan.si.unit.electric_charge.Scalar_1_0 got {type(x).__name__}')

    @property
    def power_supply_status(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 power_supply_status
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._power_supply_status

    @power_supply_status.setter
    def power_supply_status(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._power_supply_status = x
        else:
            raise ValueError(f'power_supply_status: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def power_supply_health(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 power_supply_health
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._power_supply_health

    @power_supply_health.setter
    def power_supply_health(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._power_supply_health = x
        else:
            raise ValueError(f'power_supply_health: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def power_supply_technology(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 power_supply_technology
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._power_supply_technology

    @power_supply_technology.setter
    def power_supply_technology(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._power_supply_technology = x
        else:
            raise ValueError(f'power_supply_technology: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def is_present(self) -> uavcan.primitive.scalar.Integer8_1_0:
        """
        uavcan.primitive.scalar.Integer8.1.0 is_present
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._is_present

    @is_present.setter
    def is_present(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
            self._is_present = x
        else:
            raise ValueError(f'is_present: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

    @property
    def location(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 location
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._location

    @location.setter
    def location(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._location = x
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    @property
    def serial_number(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 serial_number
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._serial_number = x
        else:
            raise ValueError(f'serial_number: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.voltage._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.current._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.charge._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.capacity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.design_capacity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.power_supply_status._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.power_supply_health._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.power_supply_technology._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.is_present._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.location._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.serial_number._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 224 <= (_ser_.current_bit_length - _base_offset_) <= 4320, \
            'Bad serialization of voltbro.battery.state.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> state_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "voltage"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "current"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "charge"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.electric_charge.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "capacity"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.unit.electric_charge.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "design_capacity"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.electric_charge.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "power_supply_status"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "power_supply_health"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f7_ holds the value of "power_supply_technology"
        _des_.pad_to_alignment(8)
        _f7_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f8_ holds the value of "is_present"
        _des_.pad_to_alignment(8)
        _f8_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f9_ holds the value of "location"
        _des_.pad_to_alignment(8)
        _f9_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f10_ holds the value of "serial_number"
        _des_.pad_to_alignment(8)
        _f10_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = state_1_0(
            voltage=_f0_,
            current=_f1_,
            charge=_f2_,
            capacity=_f3_,
            design_capacity=_f4_,
            power_supply_status=_f5_,
            power_supply_health=_f6_,
            power_supply_technology=_f7_,
            is_present=_f8_,
            location=_f9_,
            serial_number=_f10_)
        _des_.pad_to_alignment(8)
        assert 224 <= (_des_.consumed_bit_length - _base_offset_) <= 4320, \
            'Bad deserialization of voltbro.battery.state.1.0'
        assert isinstance(self, state_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'voltage=%s' % self.voltage,
            'current=%s' % self.current,
            'charge=%s' % self.charge,
            'capacity=%s' % self.capacity,
            'design_capacity=%s' % self.design_capacity,
            'power_supply_status=%s' % self.power_supply_status,
            'power_supply_health=%s' % self.power_supply_health,
            'power_supply_technology=%s' % self.power_supply_technology,
            'is_present=%s' % self.is_present,
            'location=%s' % self.location,
            'serial_number=%s' % self.serial_number,
        ])
        return f'voltbro.battery.state.1.0({_o_0_})'

    _EXTENT_BYTES_ = 540

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8iT%E40{`t>TWlQV72dgTu3jf3F$9_k3CRYM#XtautGP6CbvUU-0J&15@$Bxz|Csg8YGyXrRgp}kB7;WiR7@qe>VwrMOMUTM'
        '-IwB)g8WqZp{o4ohd%hBRjr~{ekwix&aS;z$GHozC3|Mi?LYtd&VM<p<4O4!7oJR1eu87AiM*FDWDL)8ZL?ti$jlb3jFEH3N{(my'
        'Rut@e-745)^qPNbqGUy%L}xyT-jC9OYS_i1<wh(K?7Qr{<(yx3tws^WD4Jtr;?Omx;AdSYlQn(cawjsLZ*tQ~<C^7qwo~Lrw0ElS'
        'pF|));=|~JDA;3=f@^2XzU4(%$YKX~H>9FKxoBI3{H71PjlAibhR+>iT1;fSgNMrIwVYYZcy^{-wEYbC&>XQcmvd&pq)F{%`)gjX'
        '?kf>HRMqV1<U+~iL9(xr3%f2B9Mf+M#U3MT`$oYkj`%DBo!rWqo^Omfd2;J`aCoq$&ebxn5f3?wVv+c1^kx*?XHd+FdDG3;8=4|J'
        'W9A4=pq%FeUv<r#Pcif;wim1KWaH!RME%cKUwxGT;X^W8&Qd63KKCe)jl7eKf&>xG;9y<gjqF5><NFbNiXHQ4E_tiuS~<cnAAJ<;'
        'H?G>_R^BK%u5Z}+=u*&acuv{PS;Qz<M#&^k1C2ilc9y&xq|6#0<kU|nGQ#6DHgkBMsFWj=5m6w%M>9}3X7oH-DrXCJ&Ty@fa)FPz'
        'i70W^7)a9bY%;{bq`|6iMnP8$Xy%DbZ-&Db`8=8j4Q6`em}?b%j^i~uXGI^e^X%y$RhetN0E)zp^X@vMsMWNwf+Lmb8opz=j^kHs'
        'c_ovqvlr9sCH6AwXRokV*=y|eiX*a-Ezl%R)pBYRTXM^9{u~8+U$y-=DxWXY$7*&3lHru1K<{M4n;6SF6hWFdT4N4nEYFMYmn_%x'
        '9k+f(=a@}vhg}J}2F-llE{?Pau`K6aDi>(F6U|(*aLp`~t>|Y_8uZZ1(h4udh9XFovozf?yU5d@Ud(a+qVXj_uyXC)hBaO?i<M2_'
        'QaS5oE9torWeyKfHdbQYYChGpnyrGBqx8)gxw6YKzW%aiC#r9!Kxe1fW9;k{JI8vrUOB2cMiHoaX0m5!h5Us5*kgSku?v^jb1j&&'
        '@3M<Qs@c1U4e(@OP{}~{M#qF})!fWHcDZeav3J-HDl=n0WX1-B`HeRgGvBQt#>O~MtVmIC=(j{Xw+@R9k2_=WNJlJ~>27C-y(uWP'
        'oKr41W7!5QX4!A9gGE=9ciV=dMe!~pq1OCu2IAMmOy*45b8LU2J-aJ!dG<)r=q$B~rd~yJ<9N$>@rL@nqHm2@Zr@fw9uK-N(?C|f'
        'D%@}+61>SOyp<U#@zzm~-(T5ZI^!4YsylMk*sCb$uKCrt<F^O2t%c;q%x(vg$$BJ{gk-WA$%7^5J<Bz`a;a39;HSJ__F55HY>{M^'
        'S)e1dt>lpgN#Dw`qEm22CfZByw&^T%E$=!D`$$VF(6x_m?OR-yj&``Oxvn`81xMa7iAt3CNPC4-8?R0K3|ePn{FII_aL0p#Zx_Ao'
        '<y5e1Gs7_<1P5w|;#Gb_j17)zLL#xDn<CvaAn*%UoRw{Xz7iaI%_;KRPqFPm%E#sBC~cJd?$D49DV`4XrjER67Duc%t&-*2olfO<'
        'D~Babp-pa8@+!d`OjHsp4FcyRLJ+G@sq!Rv#1P~vP1&G<1ab&!{8{AhS_2OhP(w&o^>(%JKqD_;_l7=E=<}Yoa<B__hp;#1CHYwU'
        'I?BNw*c-zB2D?NhTGy63un+c!kgARmLics0p^HF)11%#Fhv)~lr4QY3AcXs3S(*5Ix$dED>%u{}FNDKweIPFJj@*zfI0T17=&41T'
        'e7XOI_2CHggz!K|pGboEM{mk5+z$_g@L)r{h)eb!x@miG6dnxWJ6rloQY3Timd1dG;5#Ac8?ohHAHQXbaE#7;csRDBZ{<H9{lsk<'
        '501mbA)Ks@S%(9U(j&KR3^)NNLpXI^WJp6NX_7sCTgQe+;8Y0d+B~b6ow@B}z-dT_@aVSZNg5>o*d6f$&cLG~oZZCsB-u>Y<9qIo'
        'jSG*#*$^@}6bI5GoyYH}PjC)0A@pwMK|0QaC+_&D@Hq5_@Z=3ggfvO-sk`DIJONLJaK1HT&XVokTGl*$*L;De;Cu+r+*Hg+n{=PO'
        'tG>e1@JtAOjoH=9^XtN0_XD1Vz7U?f>DZA4(trM*_zf4}xe#9HoQLOWj6R-=FWxi%;CXl<gqLn9zGQ`LynIjR058HzA@sN8ETLa!'
        'ZiS2q5fd^dR4OnaiAfQYGOjC_R3U{a5mPdzROrDT5qo6pQE^=Z9d!|P8FdxXm=-ZDV_Jn?>=m(B#$FZruusH38T(Y|$9@s}W$agB'
        '00%@Ika0kTK^zouP{u(OhHyy4AsL5M7{*}{hh-dAfgux-$;ebFVM)Z2j3pJuaa_c48OK$a#7Pk+Wt>!D3a3Pzl5t9f5JM3|8ABDO'
        'aazP_8K+g4!5I-}WSmi97H37Am2p;uIh+%5PR2PE=5b!cc^T(bSil7l7i3&eVG$QaT$FK9g(X}PaY@D{6_#;X#AO+mRan6l5m#hf'
        'QDGHVMO>9}RfRQN6LC$(H5JxzUBq>YCq-AlgoFtN6B;H3OiGxfAZwTsFePD1!IXwQ0`^GQqhODQx`4Wbx`MifX#vv`rWH(U*ehVK'
        'guM#(YS<@WpM-r1_G#EJV84X@3ifL_AmD(60}2jkI4Iztgo6qWYB(g|kc2}D4rw?n;IM?l3Jz<?1Y{C21(}8=0ZS5=6f9{tF5tL?'
        ';|h*zI4R(ygp&$RYB(j}l!Q|XPH7kl7)lr_7-~2z;IxF(3QlV{BjAjLGYZaVI4j_+gtH3HYB(q0oP=`<&S^L=;Jk$M3eIb|AmD<8'
        '3koi1xG3PFgo_F;YPclel7veNE@`+d;If445-uyatl^4)D-y0KxT4{zfU6R&D!8iQnt*E(t|_>t;kpo(vzEt;=oA&vsjpKJo#e&S'
        'P7!?<is)1vhn*t&4iwRJ1&^b9TZ?G@dI$3zD5CX79KNwdw7&Vp$G4`4=5sztmeY;+eyfXU9+Pw}6LyN|rXspAV|I$@8!e*aT_#Pu'
        ')J_q73q^E%D(w`}ccX~j+!5=G==u_x>SjzPYc;f3t)W#aJa{F|i|9%*E#J#Bn#yOYqj@ncw=bi4`CP4}cgpB*Y8f5Z&{RxsyNs^('
        'Gqm<`jQ&<gB-sD9XvO(k&=vO*wCUOiK7K`i`>l(8=d5DR$y<5dt4Qk3Ro%D7{mkymb}?t^KC@~Z+tXdE+R#Aqrl*^FexhiO**U$^'
        'dBAnE6Tao0)oq`P7ad<OmJ5Y*zU7YDMc!nX(ciG&we&%g_k~m~XQHhdNUGfsH`z5ZdVmM1)+w_2Wkh|eNV4GMDlG@CZ5r#u-WNAn'
        '7{&5fmN({BWGs$AntALn`z7<)r|ehkPi%pG&OT%RU|+C*v466Evo-b~_T}gwxCj3o{Ubd_KczqAwt&SAd0E$q0<GH58wL9-9lcxh'
        '+_Y0t;x^#sfQ^1eV{fO=W`j0*sMf_X+Cy)=>0(Fz>n}gtp#_fpJpRV6pQ!zt)S7S;`FFAKFj0qFg`3D#;Yp%SwhA|qtHLuxooN+r'
        'BL6)Wo+avRt8f#!Dm+KjxmMvOa#eVqsPnDDP2{TZ0#O%Qg&WDEzb9~F`6b$qmXfUsP4qgA72>R<S~Z&J@y^Efu)QqBd&knWPx-V*'
        'Ezth-1?^31>`U5`_-=IDH?qn;Gx}%#=kwZ*bE{icpc!-~@kTnDWN_HXSO0gy<?VWTdbH^})7k0KF79#1ma{hNrKMYRQ&`_HK6-*)'
        '@j-E`zOfjK+PBkQ1(X;;op+UWw{p31=KpZmX<<Y%000'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
