# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-08 16:00:09.566738 UTC
# Namespace:     voltbro.freeflyer.motion

from voltbro.freeflyer.motion.control_1_0 import control_1_0 as control_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
control_1 = control_1_0
