# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/freeflyer/motion/control.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.567195 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.freeflyer.motion.control
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class control_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 front:       None | uavcan.primitive.scalar.Real32_1_0 = None,
                 back:        None | uavcan.primitive.scalar.Real32_1_0 = None,
                 side_top:    None | uavcan.primitive.scalar.Real32_1_0 = None,
                 side_bottom: None | uavcan.primitive.scalar.Real32_1_0 = None,
                 top:         None | uavcan.primitive.scalar.Real32_1_0 = None,
                 bottom:      None | uavcan.primitive.scalar.Real32_1_0 = None,
                 impeller:    None | uavcan.primitive.scalar.Real32_1_0 = None) -> None:
        """
        voltbro.freeflyer.motion.control.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param front:       uavcan.primitive.scalar.Real32.1.0 front
        :param back:        uavcan.primitive.scalar.Real32.1.0 back
        :param side_top:    uavcan.primitive.scalar.Real32.1.0 side_top
        :param side_bottom: uavcan.primitive.scalar.Real32.1.0 side_bottom
        :param top:         uavcan.primitive.scalar.Real32.1.0 top
        :param bottom:      uavcan.primitive.scalar.Real32.1.0 bottom
        :param impeller:    uavcan.primitive.scalar.Real32.1.0 impeller
        """
        self._front:       uavcan.primitive.scalar.Real32_1_0
        self._back:        uavcan.primitive.scalar.Real32_1_0
        self._side_top:    uavcan.primitive.scalar.Real32_1_0
        self._side_bottom: uavcan.primitive.scalar.Real32_1_0
        self._top:         uavcan.primitive.scalar.Real32_1_0
        self._bottom:      uavcan.primitive.scalar.Real32_1_0
        self._impeller:    uavcan.primitive.scalar.Real32_1_0

        if front is None:
            self.front = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(front, uavcan.primitive.scalar.Real32_1_0):
            self.front = front
        else:
            raise ValueError(f'front: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(front).__name__}')

        if back is None:
            self.back = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(back, uavcan.primitive.scalar.Real32_1_0):
            self.back = back
        else:
            raise ValueError(f'back: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(back).__name__}')

        if side_top is None:
            self.side_top = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(side_top, uavcan.primitive.scalar.Real32_1_0):
            self.side_top = side_top
        else:
            raise ValueError(f'side_top: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(side_top).__name__}')

        if side_bottom is None:
            self.side_bottom = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(side_bottom, uavcan.primitive.scalar.Real32_1_0):
            self.side_bottom = side_bottom
        else:
            raise ValueError(f'side_bottom: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(side_bottom).__name__}')

        if top is None:
            self.top = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(top, uavcan.primitive.scalar.Real32_1_0):
            self.top = top
        else:
            raise ValueError(f'top: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(top).__name__}')

        if bottom is None:
            self.bottom = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(bottom, uavcan.primitive.scalar.Real32_1_0):
            self.bottom = bottom
        else:
            raise ValueError(f'bottom: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(bottom).__name__}')

        if impeller is None:
            self.impeller = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(impeller, uavcan.primitive.scalar.Real32_1_0):
            self.impeller = impeller
        else:
            raise ValueError(f'impeller: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(impeller).__name__}')

    @property
    def front(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 front
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._front

    @front.setter
    def front(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._front = x
        else:
            raise ValueError(f'front: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def back(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 back
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._back

    @back.setter
    def back(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._back = x
        else:
            raise ValueError(f'back: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def side_top(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 side_top
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._side_top

    @side_top.setter
    def side_top(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._side_top = x
        else:
            raise ValueError(f'side_top: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def side_bottom(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 side_bottom
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._side_bottom

    @side_bottom.setter
    def side_bottom(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._side_bottom = x
        else:
            raise ValueError(f'side_bottom: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def top(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 top
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._top

    @top.setter
    def top(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._top = x
        else:
            raise ValueError(f'top: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def bottom(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 bottom
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._bottom

    @bottom.setter
    def bottom(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._bottom = x
        else:
            raise ValueError(f'bottom: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def impeller(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 impeller
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._impeller

    @impeller.setter
    def impeller(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._impeller = x
        else:
            raise ValueError(f'impeller: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.front._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.back._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.side_top._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.side_bottom._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.top._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.bottom._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.impeller._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 224 <= (_ser_.current_bit_length - _base_offset_) <= 224, \
            'Bad serialization of voltbro.freeflyer.motion.control.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> control_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "front"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "back"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "side_top"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "side_bottom"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "top"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "bottom"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "impeller"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = control_1_0(
            front=_f0_,
            back=_f1_,
            side_top=_f2_,
            side_bottom=_f3_,
            top=_f4_,
            bottom=_f5_,
            impeller=_f6_)
        _des_.pad_to_alignment(8)
        assert 224 <= (_des_.consumed_bit_length - _base_offset_) <= 224, \
            'Bad deserialization of voltbro.freeflyer.motion.control.1.0'
        assert isinstance(self, control_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'front=%s' % self.front,
            'back=%s' % self.back,
            'side_top=%s' % self.side_top,
            'side_bottom=%s' % self.side_bottom,
            'top=%s' % self.top,
            'bottom=%s' % self.bottom,
            'impeller=%s' % self.impeller,
        ])
        return f'voltbro.freeflyer.motion.control.1.0({_o_0_})'

    _EXTENT_BYTES_ = 28

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8iT%E40{_)kTW{P%6yDHecboJUg{B}7-M*Am6hqo7fl5GVN+j4OL@7l`C7q7#$)2IM$Bf6zE>PN35E3*JkutnhqCcfSCI2Lx'
        'vAxM&l2$^zu+qxobNPHO-#PZ<;lDOUOW9AKkK2CY2M$S?<TT(vQa4}@@kAJlgezwB$(t<TAs+p&+A%Xb=F+-(Xr^?T@F-%^KuMpx'
        'tz_z{RI*-^5faf5A!<z#C|3$+O)|C?w3&25p}2?~Pee+J!00MzGMS*r;#Iyb&O4?)R4;9qb)&}!RZ4O<RV*>92!2H5`&LGeEN~Y1'
        '2jPqopDId}jS(uj5JvS|DQ$W*a$;%I<W1%z9u25;Ru~PgUNLY2PIbb7@l^w73)k0<ieVqg=;I54psKelW5nf(1T1POF!dV7<<Ufu'
        'Q1}?v1wFakakp;HJn9y$3X4(t&8!&xDoGTLd@B8JpiRUHX(Qq)_3eY#B=u~K6D;mRaYl?k#!KD5y}i9seP{z=Qx|J7(xgF(-owNf'
        'p3yU(wa_tW*CdN2OIW0Af;Ao~*1#5BuibrjdS-TZ_R93k<=Q))<0@iNJ<-)L;<j@tJT!0>&L>y`-y(VxX=S$bDYC{}%qOvsig4d7'
        '>2Z>XRC){*0V6TR1a-w;0`6jR%Sg`FvX$;&L5JSMh(TDYm62x1B%@#X0TUmwy~gVsaq0%#Ba$`Jz&`VU38*dS1VGrX#+7pt7=1dY'
        'fivyA@7QJ=WqU9|fF>B1#G2UdH@U~m7F^RMqt9fy<}(zbKIiL;pHeQ!#`L)?TcQM!LZ}QXi7BGPM^o@Id;)XuDcpd0xS0hqOxyr-'
        'xY%Lh0V6Oh)qijFi5pzq%I<IDZNW)>jEETL^eB*|9l8Pwh<PuvP$17Oo4$;hq)N!{o!|k-k%Mpb>1FEsJZcOW0kzttG{C&u{aQrG'
        '8ThA}s@Jv?7Z*dE1DSd?burzLM|NoNKwI`uv4ewMwcewIwPG4&yJIPJ6E`RIn#46@;2PBNet&x5b<_>J)O&Eas+w@0VIShd)nl33'
        '6-tTlaEoI{`j%hhR^?&Lg21lUOwC}%DkV%p3JJ8J2|qy_eu1B19Uj52@Fax~w&24hxZXn%T`AUXwhW5JixtjSFVeJFzP-$bFShJs'
        ';g;p>OAsoZ_03?Vmz^6K)E)RH%M9+qz5V8U`=@(dgg84dBD)QuLz$(I=fuKkv$OOPw5Rz)|Ng&Q5(q5kA*|OR!oNV{?~&F(SYoAf'
        'D4jcyc8vSPh4Foq-XApX6BovhQTlk$xKCUdKSSxWLE}DgVf-AW&j*eB#D(!LN_Pj1d&T*X!x+A%&)C=V6wXP4Gt$QScmz-W?exF~'
        '{0^J2^&ig!t}E6;nk!S^)sy%Z%)hN90Y-hi<R2#&^u!(9VvUITpXcw|o-YWvh-`QpF4c$Z_W)ep#0nfbYuyZM<mc}?o3&^B&aKd>'
        '!B$wz6hCUUKgc)ko9NJuRo%`y5Y|hbw$!UuUfNEw{^YGh1}~O|2DR4L`3I!o(u$D^000'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
