# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/config/dc/get.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.533208 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.dc.get
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import voltbro.config.dc

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class get_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self) -> None:
            """
            voltbro.config.dc.get.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            """
            pass

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            assert 0 <= (_ser_.current_bit_length - _base_offset_) <= 0, \
                'Bad serialization of voltbro.config.dc.get.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> get_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            self = get_1_0.Request(
                    )
            _des_.pad_to_alignment(8)
            assert 0 <= (_des_.consumed_bit_length - _base_offset_) <= 0, \
                'Bad deserialization of voltbro.config.dc.get.Request.1.0'
            assert isinstance(self, get_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
            ])
            return f'voltbro.config.dc.get.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 0

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8iT%E40{?YVO>Yx15Z$(EQ@%kJln)^|q4cuAfeS~j3n6L|H)PrCX>7^6Ui=Xfq)POHK(Yi<hJVTrV7y5MD(YVB**Bi|-pqU%'
            '{QA9F^j~_^Eu@#GWFDO6Mt|nQK*?&`bk^$tn64cK7wZrmyjygDOFTHm6C9;&*7An%hcjz}aJH;%d#tCWtjj5c@(?~o@Bz~<n}PG%'
            'wy26Ue80XgvD&DLuXu{-3gaO-En)zVA299x6Em?`(VXNw37vzQ2axzZU1!I74w7}&1*RpA(=Fz0bTtrQfOR}5Ov8K_Eihf0kfHe`'
            '|6P*&ji;Cf%4P>Uq@FZl+Wh1(Z3nVR=Wy+d@Rc*dWsT`-cK5t|R_4B8z{9LqaZiK}+K?ML(>36?G+@%wg96jd-o&b_EhS~2qYD|f'
            'h=KUeItXdMH^YKu&f3t|@*O7*b$g`lsC{);-Bb6~gI>&l2}AOqoDEj!zznogD&R@^xtRRC(&2R<A5pj-Z`xwE!}R!~B7V^bYcz@7'
            'djpN7wFxxUw;ebhtoyqpJFHgPNK`M<jR}`hx6}WU)XR*HqcPkq&ZAUe#!UqLfupMU=>_dmw<?6yZWLs<(JfX*zVLaz3|V7kG(5k)'
            '%wXQ}wqLn%6kbG8{sAFQs;vJ4000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     config: None | voltbro.config.dc.pid_config_1_0 = None,
                     report: None | voltbro.config.dc.pid_report_1_0 = None) -> None:
            """
            voltbro.config.dc.get.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param config: voltbro.config.dc.pid_config.1.0 config
            :param report: voltbro.config.dc.pid_report.1.0 report
            """
            self._config: voltbro.config.dc.pid_config_1_0
            self._report: voltbro.config.dc.pid_report_1_0

            if config is None:
                self.config = voltbro.config.dc.pid_config_1_0()
            elif isinstance(config, voltbro.config.dc.pid_config_1_0):
                self.config = config
            else:
                raise ValueError(f'config: expected voltbro.config.dc.pid_config_1_0 '
                                 f'got {type(config).__name__}')

            if report is None:
                self.report = voltbro.config.dc.pid_report_1_0()
            elif isinstance(report, voltbro.config.dc.pid_report_1_0):
                self.report = report
            else:
                raise ValueError(f'report: expected voltbro.config.dc.pid_report_1_0 '
                                 f'got {type(report).__name__}')

        @property
        def config(self) -> voltbro.config.dc.pid_config_1_0:
            """
            voltbro.config.dc.pid_config.1.0 config
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._config

        @config.setter
        def config(self, x: voltbro.config.dc.pid_config_1_0) -> None:
            if isinstance(x, voltbro.config.dc.pid_config_1_0):
                self._config = x
            else:
                raise ValueError(f'config: expected voltbro.config.dc.pid_config_1_0 got {type(x).__name__}')

        @property
        def report(self) -> voltbro.config.dc.pid_report_1_0:
            """
            voltbro.config.dc.pid_report.1.0 report
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._report

        @report.setter
        def report(self, x: voltbro.config.dc.pid_report_1_0) -> None:
            if isinstance(x, voltbro.config.dc.pid_report_1_0):
                self._report = x
            else:
                raise ValueError(f'report: expected voltbro.config.dc.pid_report_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            # Delimited serialization of voltbro.config.dc.pid_config.1.0, fixed bit length 192 (24 bytes)
            _ser_.add_aligned_u32(24)  # Delimiter header is constant in this case.
            _ser_base_offset_ = _ser_.current_bit_length
            self.config._serialize_(_ser_)
            assert _ser_.current_bit_length - _ser_base_offset_ == 192
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            # Delimited serialization of voltbro.config.dc.pid_report.1.0, fixed bit length 128 (16 bytes)
            _ser_.add_aligned_u32(16)  # Delimiter header is constant in this case.
            _ser_base_offset_ = _ser_.current_bit_length
            self.report._serialize_(_ser_)
            assert _ser_.current_bit_length - _ser_base_offset_ == 128
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 384, \
                'Bad serialization of voltbro.config.dc.get.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> get_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "config"
            _des_.pad_to_alignment(8)
            # Delimited deserialization of voltbro.config.dc.pid_config.1.0, extent 192
            _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
            if _dh_ * 8 > _des_.remaining_bit_length:
                raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                        f'but the remaining length is only {_des_.remaining_bit_length} bits')
            _nested_ = _des_.fork_bytes(_dh_)
            _des_.skip_bits(_dh_ * 8)
            _f0_ = voltbro.config.dc.pid_config_1_0._deserialize_(_nested_)
            del _nested_
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f1_ holds the value of "report"
            _des_.pad_to_alignment(8)
            # Delimited deserialization of voltbro.config.dc.pid_report.1.0, extent 128
            _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
            if _dh_ * 8 > _des_.remaining_bit_length:
                raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                        f'but the remaining length is only {_des_.remaining_bit_length} bits')
            _nested_ = _des_.fork_bytes(_dh_)
            _des_.skip_bits(_dh_ * 8)
            _f1_ = voltbro.config.dc.pid_report_1_0._deserialize_(_nested_)
            del _nested_
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = get_1_0.Response(
                config=_f0_,
                report=_f1_)
            _des_.pad_to_alignment(8)
            assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 384, \
                'Bad deserialization of voltbro.config.dc.get.Response.1.0'
            assert isinstance(self, get_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'config=%s' % self.config,
                'report=%s' % self.report,
            ])
            return f'voltbro.config.dc.get.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8iT%E40{_id>u(fQ6yHMMJla}$BnYful$QgA()u8#f>d#7Z3_B9LoRn_Zui_}c4jhjXX#=fZA74ORgzx6*Tg@-KY>4m4;nw1'
            '_*oN^dhX2Zd%LTE(MfjZ&N=6vx#yhUdF)E>cR!A1;!7U(%XVlx1_@cfsl#tk(_sd&yrS=gTreefT@gWKi6~%K%RW=<>gcMvt&Ye('
            ';?g4W50yMen1N?lp1Z{JhHV*nCX7WE`kou2z#u8HAmpB_AR`ApP1oxx*OSZKQ>#kuAXJEen~`9lx`wK^I8;?i$-Y_69J_XyVPaE3'
            'iO?s+uk3oCIlPF+w;RvgPq^!{K*6?z0Dbb6*5mu!Cdr$E0T`;B6L#X+U^Lx1UZ>+wL`xQR4L{Hy<t1i>7IkQVPN2@2(=A$RO13h!'
            's!7SAS;wQI(T*L&<bpWN%?nVuEShi8P>`Z$qxnbW-i69`z0J6QygAK6pJ%>Oi%PysLP1@d26nxo2dJk=^DY;Wtv|dJP)lH}LX6>T'
            'x<(xj$1?TT=H_N5*K-fmMke~AuSA^)clQ$8vy_~=xQrW}ayDRoz(VE<ZD5wWg5?njZ)ZP$V`6H0diwOl)QRlz%JLfOqH??r7sM<l'
            'c)P9O9e6!N7uZ^(MKQ=~P3|U3e3{wA_X0t<t>)zz3B4$=7&072e2NCj0sU~eiN-A;yq6a=bsZhra}rMsp2l-Of&l@m<hGk=c%Oz8'
            'J`ebj>2Qk#EFU@gn>D~8w?6>@s;vuLe*yv}M-mtq6UHe+2U`gpgK+{h#B&Ac6CM2$x0qUkb26jkXl!eeg)Z`wwCMbm{uFFX?u)G@'
            '!Xts_iC9(WQ`8O@kH9Q^03X67_y}@vIX*})F&(twwF(kzh`?is=65A`p6B9n{C)*rQ%uV3#PgNRZlxqF7flZxh<4AhqK7!wX!_V^'
            '0To_QpP?3T%xtjb$O5%(?&e#BfNSo2<e=T<W-e+-5csV+lFL30O{_nDqDbWiBNNRna#tq}F6gpe4CutcsOsIrgf08jjZ4&gWQJx8'
            '>fvJK2<|&v*N$^=1&Osf@G1)Q`y@|MZF?r~#I!pwUyAc2pblX{-~|MWT6@7E;W_9BR|h%fGk8~XZ^2=>4PU?t+<`A)74E@ZScCf!'
            '%&ftC^KiZa5pp1{h3Lez{>g2&4q2@tHi8%y*YxM$s)pxQyNB!QDTB`%LHH<Ea}BP?=70rD)fnHXu9oWJzUPAH>ZEtu0!R)e_`#&o'
            'Dbq#U_sK_p_<u^~L1@52l*>X1e>YLMjF^Nx3pI5HsWUZdMYxHa3SUR+^;Y2~aw@!n)Rk7@CUPpgfz*vw;U;n_`~;~_T7?_QNz%aq'
            'Y?}v@rh6D6d<Wrs7w$g`u;CF%_!_=>fsn<b!Ilw)Lgk*wz1WMAc_SdesEv<g5;-czKfzj(cbR=D>39u&91INWNtnp>=&lTt576$m'
            'sZb9UFIfkb`qq#g`xdF2XN$~df^St|ZzOeZKW?bkHTXF8dz8ymf{`24^vvThj!F_h4aKLe%(PBcyx3Bs_N1%*-6t;`6tIWCh{<be'
            'vcu#B$Ez`z!5ExD@55Pm^Wkddzq)?kjITDs6b=Qay3bLkj~zRE28XEl8Bb6;RSE}tGMU0YyoK#^1IGZEgZX4inVRfS;Qz+_fi7>!'
            'mvqkPR^;okIHPghzM!Q@+uhh1TM$<mLyI*cb@oxGp(_?9wM$0yZCc;X;;mERNcvxb%V+I>DXO2h|8?mZg%jH9_Ku5r|De7njxOxb'
            '8V3ry^h2j%;y3NGXLDxZEfjc>zWWK!{4@O0P*Hz<{#yD+y81IW+Nn^kbSjh^TNlbom8*wkulDg+;ih(DUpGwd)PJ&@!1$oML$~Mk'
            '2tQc;cm6K}5`JqKVxHE}XjjpQFr8cJX*<Z&)3xV}zX0kONq)N!000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'voltbro.config.dc.get.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8iT%E40{_ie>u(fQ6yHkQT?&*(1yo+^3kt|W0ozD0RuQ5OEwzC7B9}Wmw|i!tof&8DtXq^=j6h3nA_<rHNmHVcNQ_^N#t)eI'
        '!9T-4!*BK6nc3ahSBp@ilXT|pIp>~x9=~(WOlP`p{jnhxUSfwkZTN<jBR=y?YMB?QZm}H6J0;igP0plPb((o)GtbUUyG-7cyD!U2'
        'a!{-x9{Vt0J||q!AtlzF=3bEJf!8G2Lu^_?J=@BT#dXig<sEy<EaZ%QuE2P1GEyT&hLoA-n~trNrQeFzH>K94rLM}$Xb7R4d!`<6'
        '=F9U^3?zONeL6bkl9Dr+>#;oL%#d@UpG=t*W)Ro$I57=5F4hy@3A{W*hQ)|WIY^OK56jf0SUG`?S0)toCYs;1Uy5#Uln1?NJ=!S6'
        'BOm!v^eD&inU4KJe&iYQjl2}Am3KqA13496$>pT77^sg2dd%i3;3}+gR&*1?!3`-X)`d<)(YH}Z`8n9}gcW!Ko?ne16PrV42zQ9*'
        'I6TzlyA;oWCk9~)Y=v#G9d<xAG^U&A7Mj1a3IN^Y#A0><75Hd*({J?W6_cL~f1k#maeBoH;<!>|J1Oy}OS)s3XzaikD>(=+j#)kB'
        'GLLe{tAnJM<iWHI2}i`*32GRoU1$-4mlStAuq^6LH*--#nOXspU&ui%b;H*YPi~}0YMDSscT1)%wUk=Widv*e$uR<ps@;8rRa|O^'
        'kQ)zlU&kH&2yq|t;IkOx>DZ1wvAq+PBY6p{VI8bjx$970HRK|WPM8cmuZ5zI7?jg`S-r|EvxJpsG?rB_F>M>cn6PSVt5vRPkQg&)'
        'Q-8IVLfhb6yz||pX8|qeshx8@b*NcpIX_P^;OHB*4jpXKQdiQ+)tV+OtrM0*d7~ez5}1)%7TwQN>?)WVbl(-5CaT-jw%jq~jVTuP'
        'h13-V<41|lsclftNGh5|JtbPOO&%EP;3<#h74i`9nG^9EbzEPcN?r>K3n{JZDyj{1j73j`DA*;2k5_PyHJ$ZTXYsKzm2X+o=B$8?'
        '>PYszeM7?|BO?cghM&vstuD`_8VUoKBzy+84;$xT(>QEys70~G4RovzgjxZih*_>@A8qZ8vVjgHqSzZ{M2fXhP8ypG?3{yLFbKO9'
        '`WD~c8|Re4fyM@L1+Ipw4#9AkC3pdj)@tzO+Uj`3d`*>H7E2D^P?ZLnmW7k}H-@}ZaWP>u`$~buP1iCNXwgC>)&U48(Cd-{#TsqT'
        'G#6tUi!e8YS@NhwnCCej!D?zRxRN^-HWgd-%aG4h?grs2n1Xru8oq(s@Ev>$-@_gF0qzEE6AD>)5}pzR^}<^uJ)IhRU!rVVl9Rok'
        ')ErH;%#Ft!TMa|IZSNH;qt=TvNe!DNwEY$x`uqP=@>T}~!Y$@2>L^l2>(r`n6FC;XfYb}E!cF8@cm}C6t-?*@Sa=?(^R2>7<XHF~'
        'Qt!12H<F_g10B1w5%u;d1ng}D>m9iJ;4p?Cml3i!Z&?LV$fb5qY{GZ6Xsmez7&Y(_4Lny2oW(I*u$l3C)Lk3K1q7JZGE}rK)%@Y('
        'S@gSYDI}rN(x;Nuv3Zi(1vbfC#?4OeCLctv439PSyv&U-?wXdWCPT}_uODGnq68`^{@KcmyJ9tpEgk9octw^T@Hmw4-F7(!{P5vL'
        '20VDR9E@TPE@JfI6ZrJ{<<x(5{k0HY?PvCZrDyiRJ$s%%gabQ#)~0pw#jaGUID)tKGh2;ExCXP){2f00aPt>Kz8v#+G&z488(NIC'
        '{>C}jg1F)kdaMwss*hR?Gq89@g=D|Fom027cw2h@MYw#>`4^-5VdvixGoyG?dEGv6A@3jb_bAZCy-MTi;y(3IWf;Xxh3vtCS$qct'
        'mN9n4Zq%pE6noU+X}l#{YjKq_`(gWP@$s74;#PIqy2V=O%wnx`zH{rW_Pr!fpHb$&UHnq{_UsaYg{Pya&MqC*=u<mW`@s9RQQ4nF'
        'Wo?2)sQkQ!N`&j!Ojp|%nj}4r*T%LVt@Ur!M5oW7csl+EPwQxU6S*0$_N|)?|IaG!KdIZV>h{ZhW?=3<GtfTlfu8#t?CM~_(-Hsx'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
