# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-08 16:00:09.494390 UTC
# Namespace:     voltbro.config

# There are no data types in this namespace. There may be data types in nested namespaces.
