# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/foc/specific_control.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.561351 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.foc.specific_control
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class specific_control_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    VELOCITY:  int = 0
    TORQUE:    int = 1
    POSITION:  int = 2
    VOLTAGE:   int = 3
    UNIVERSAL: int = 4

    def __init__(self,
                 set_point_type:  None | int | _np_.uint8 = None,
                 set_point_value: None | int | float | _np_.float32 = None) -> None:
        """
        voltbro.foc.specific_control.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param set_point_type:  saturated uint8 set_point_type
        :param set_point_value: saturated float32 set_point_value
        """
        self._set_point_type:  int
        self._set_point_value: float

        self.set_point_type = set_point_type if set_point_type is not None else 0  # type: ignore

        self.set_point_value = set_point_value if set_point_value is not None else 0.0  # type: ignore

    @property
    def set_point_type(self) -> int:
        """
        saturated uint8 set_point_type
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._set_point_type

    @set_point_type.setter
    def set_point_type(self, x: int | _np_.uint8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 255:
            self._set_point_type = x
        else:
            raise ValueError(f'set_point_type: value {x} is not in [0, 255]')

    @property
    def set_point_value(self) -> float:
        """
        saturated float32 set_point_value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._set_point_value

    @set_point_value.setter
    def set_point_value(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._set_point_value = x
        else:
            raise ValueError(f'set_point_value: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u8(max(min(self.set_point_type, 255), 0))
        if _np_.isfinite(self.set_point_value):
            if self.set_point_value > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.set_point_value < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.set_point_value)
        else:
            _ser_.add_aligned_f32(self.set_point_value)
        _ser_.pad_to_alignment(8)
        assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
            'Bad serialization of voltbro.foc.specific_control.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> specific_control_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "set_point_type"
        _f0_ = _des_.fetch_aligned_u8()
        # Temporary _f1_ holds the value of "set_point_value"
        _f1_ = _des_.fetch_aligned_f32()
        self = specific_control_1_0(
            set_point_type=_f0_,
            set_point_value=_f1_)
        _des_.pad_to_alignment(8)
        assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
            'Bad deserialization of voltbro.foc.specific_control.1.0'
        assert isinstance(self, specific_control_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'set_point_type=%s' % self.set_point_type,
            'set_point_value=%s' % self.set_point_value,
        ])
        return f'voltbro.foc.specific_control.1.0({_o_0_})'

    _EXTENT_BYTES_ = 5

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8iT%E40{@j&Yik=v6qVzLWTo{3r70<Gv!zfR2#S*wY8nbnUAqX`k}AuFQo=C1JJKDpyR)5{Rqd8Q^Px#xhPL48*Fs<PXS#P*'
        'k|n<=URZXX=bpK9?%5w^e(Mzr`D1RU2cZh1Dp5>w8u9O_AF(P4M4Sr6HM8dR9WAp!XOeXeQf80ro#*zMT`{vHp)t<C-4~JerKomA'
        'P*o`lc$WtVkZ36)Yf7Zgq~ap6P%y>4Vf)C|r|N|l_PI6J3DsJ1KhsRvCkT8ArIS_G%x-cPg<~pZ5>icxcKj~eo=P5b&HK2bvYRO0'
        'OITP-H0v>W`drtE&ozly($iq;B?J$s(j*okvv9-QY>j~2w(2_0ZM!KvQQ=41w&n&=nkFHY;Uv(j%!gUCpqM79;E5iRogtwJta)vR'
        '>6RPLso>J30U4-Z#QDugP<@Id+^T!<7Q73$Um?Gk_7bi$Bw^;ek_H+xtT6MN!!~aFX}K`@93LMS>QgU}Zcb})Osh|$4A1$VDY&Tx'
        'Q(8wXJdYm7uE5O`7NsGJ9Hz9lvDI9!b-u#=uxjRpVCJ3Cjj;VxGUWtt>OM+s>S)qv6a&`aZhc5l`H21C|3c4on(Z%lH}b%^`_UL?'
        '>MAg$R&%G;sWlrH0A0HZP;sxh)p`8IMTDlWf-}F{sO@dEcOGwDfHX5kVx}@tM#MiD6sJS<U>WYg`|uGwgwNqq*oGSHK^q8souSx6'
        'hIbNB%|d%<7D$)xvk<i)HQ}Lcm}R0wCIf~O5hE!@DVw7EMBGQYwa_H?TW<6SOK0jHDjI}yg*kKtEPQLOeT!0@b!x|Nap)D+On05`'
        'Z=Lmv>iz0!)rrMwS4$NFRAE%fP?}iJeI77-i0b@fBgtYWbKQ8k%#^3;Q<ivLDPj-F4I`BqF7$$kD&<WU*~eantu>-O@B6anc_Zn1'
        'pLnZx-M~Ol*u9^3N5a5?2l>G8g0cTF@1I;0j(k{t_Q;y0{0;_In&1Hj?shf>OXn<;nK$!96D^1oLgz3lrFe9Bx&jfzkbr;`zR7bm'
        'L;MI+`@yKl#-@WA(`WnWHJ@?4mG?0pqlz=rM5NYumw~8**cTB;zLjkj3p7=i`DW^_K*+Iq&XE8(S~I*fi!B<4Jn5ZV1O^UIS})BT'
        '=rB%y$%T++et?JyaOs=a`SS$EVk3(pDi6-?hP7YpO1<=}^6@{E4*1}oC-X6DF;ASmV}tIyM$uV(7Eu?p?5v6=`LC*hh4}jfnulmi'
        '`S4eL1^&kOADsBtE&8)w%FYkF>a6|;m$Z$Vat8na'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
