# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/brover/ws/types/voltbro/foc/state_simple.1.0.dsdl
#
# Generated at:  2025-09-08 16:00:09.563398 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.foc.state_simple
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import uavcan.si.unit.angle
import uavcan.si.unit.angular_velocity
import uavcan.si.unit.electric_current
import uavcan.si.unit.voltage

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class state_simple_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 angle:                None | uavcan.si.unit.angle.Scalar_1_0 = None,
                 velocity:             None | uavcan.si.unit.angular_velocity.Scalar_1_0 = None,
                 current:              None | uavcan.si.unit.electric_current.Scalar_1_0 = None,
                 bus_voltage:          None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 current_coil_voltage: None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 has_fault:            None | uavcan.primitive.scalar.Bit_1_0 = None) -> None:
        """
        voltbro.foc.state_simple.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param angle:                uavcan.si.unit.angle.Scalar.1.0 angle
        :param velocity:             uavcan.si.unit.angular_velocity.Scalar.1.0 velocity
        :param current:              uavcan.si.unit.electric_current.Scalar.1.0 current
        :param bus_voltage:          uavcan.si.unit.voltage.Scalar.1.0 bus_voltage
        :param current_coil_voltage: uavcan.si.unit.voltage.Scalar.1.0 current_coil_voltage
        :param has_fault:            uavcan.primitive.scalar.Bit.1.0 has_fault
        """
        self._angle:                uavcan.si.unit.angle.Scalar_1_0
        self._velocity:             uavcan.si.unit.angular_velocity.Scalar_1_0
        self._current:              uavcan.si.unit.electric_current.Scalar_1_0
        self._bus_voltage:          uavcan.si.unit.voltage.Scalar_1_0
        self._current_coil_voltage: uavcan.si.unit.voltage.Scalar_1_0
        self._has_fault:            uavcan.primitive.scalar.Bit_1_0

        if angle is None:
            self.angle = uavcan.si.unit.angle.Scalar_1_0()
        elif isinstance(angle, uavcan.si.unit.angle.Scalar_1_0):
            self.angle = angle
        else:
            raise ValueError(f'angle: expected uavcan.si.unit.angle.Scalar_1_0 '
                             f'got {type(angle).__name__}')

        if velocity is None:
            self.velocity = uavcan.si.unit.angular_velocity.Scalar_1_0()
        elif isinstance(velocity, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self.velocity = velocity
        else:
            raise ValueError(f'velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 '
                             f'got {type(velocity).__name__}')

        if current is None:
            self.current = uavcan.si.unit.electric_current.Scalar_1_0()
        elif isinstance(current, uavcan.si.unit.electric_current.Scalar_1_0):
            self.current = current
        else:
            raise ValueError(f'current: expected uavcan.si.unit.electric_current.Scalar_1_0 '
                             f'got {type(current).__name__}')

        if bus_voltage is None:
            self.bus_voltage = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(bus_voltage, uavcan.si.unit.voltage.Scalar_1_0):
            self.bus_voltage = bus_voltage
        else:
            raise ValueError(f'bus_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(bus_voltage).__name__}')

        if current_coil_voltage is None:
            self.current_coil_voltage = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(current_coil_voltage, uavcan.si.unit.voltage.Scalar_1_0):
            self.current_coil_voltage = current_coil_voltage
        else:
            raise ValueError(f'current_coil_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(current_coil_voltage).__name__}')

        if has_fault is None:
            self.has_fault = uavcan.primitive.scalar.Bit_1_0()
        elif isinstance(has_fault, uavcan.primitive.scalar.Bit_1_0):
            self.has_fault = has_fault
        else:
            raise ValueError(f'has_fault: expected uavcan.primitive.scalar.Bit_1_0 '
                             f'got {type(has_fault).__name__}')

    @property
    def angle(self) -> uavcan.si.unit.angle.Scalar_1_0:
        """
        uavcan.si.unit.angle.Scalar.1.0 angle
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angle

    @angle.setter
    def angle(self, x: uavcan.si.unit.angle.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angle.Scalar_1_0):
            self._angle = x
        else:
            raise ValueError(f'angle: expected uavcan.si.unit.angle.Scalar_1_0 got {type(x).__name__}')

    @property
    def velocity(self) -> uavcan.si.unit.angular_velocity.Scalar_1_0:
        """
        uavcan.si.unit.angular_velocity.Scalar.1.0 velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity

    @velocity.setter
    def velocity(self, x: uavcan.si.unit.angular_velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self._velocity = x
        else:
            raise ValueError(f'velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def current(self) -> uavcan.si.unit.electric_current.Scalar_1_0:
        """
        uavcan.si.unit.electric_current.Scalar.1.0 current
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._current

    @current.setter
    def current(self, x: uavcan.si.unit.electric_current.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.electric_current.Scalar_1_0):
            self._current = x
        else:
            raise ValueError(f'current: expected uavcan.si.unit.electric_current.Scalar_1_0 got {type(x).__name__}')

    @property
    def bus_voltage(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 bus_voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._bus_voltage

    @bus_voltage.setter
    def bus_voltage(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._bus_voltage = x
        else:
            raise ValueError(f'bus_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def current_coil_voltage(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 current_coil_voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._current_coil_voltage

    @current_coil_voltage.setter
    def current_coil_voltage(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._current_coil_voltage = x
        else:
            raise ValueError(f'current_coil_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def has_fault(self) -> uavcan.primitive.scalar.Bit_1_0:
        """
        uavcan.primitive.scalar.Bit.1.0 has_fault
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._has_fault

    @has_fault.setter
    def has_fault(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
            self._has_fault = x
        else:
            raise ValueError(f'has_fault: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.angle._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.velocity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.current._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.bus_voltage._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.current_coil_voltage._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.has_fault._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 168 <= (_ser_.current_bit_length - _base_offset_) <= 168, \
            'Bad serialization of voltbro.foc.state_simple.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> state_simple_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "angle"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.angle.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "velocity"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.angular_velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "current"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.electric_current.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "bus_voltage"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "current_coil_voltage"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "has_fault"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = state_simple_1_0(
            angle=_f0_,
            velocity=_f1_,
            current=_f2_,
            bus_voltage=_f3_,
            current_coil_voltage=_f4_,
            has_fault=_f5_)
        _des_.pad_to_alignment(8)
        assert 168 <= (_des_.consumed_bit_length - _base_offset_) <= 168, \
            'Bad deserialization of voltbro.foc.state_simple.1.0'
        assert isinstance(self, state_simple_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'angle=%s' % self.angle,
            'velocity=%s' % self.velocity,
            'current=%s' % self.current,
            'bus_voltage=%s' % self.bus_voltage,
            'current_coil_voltage=%s' % self.current_coil_voltage,
            'has_fault=%s' % self.has_fault,
        ])
        return f'voltbro.foc.state_simple.1.0({_o_0_})'

    _EXTENT_BYTES_ = 21

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8iT%E40{_)k&2QX96yHsg-F%fMN(+b<2q1+ZB)1hH@l9x?a9A1wsQ?v4)3H6fZx-8Q+2d^%DN=f%YS2g^WhzccmALfG5yXiT'
        '{{cr3969k1gg3UcAKu+02U>}hqKw~r^Za}7_j{h%9l!hS=~DVrPls(cc0G&4EaKGTUr^g)7IB0hikM5L)#*(cC5}uYcC8&Uy{})m'
        'rFZnQnjiu7(f@c$c+!r9RTqvGODY+OxgUDynj|e2#asj$N~-#CzTVfha;<b*-_mM^P$?sBCz8c_3zLq3(}~h*VvRG;?ZTKQE|ru>'
        'gAK+qBTT6C32iwvuwrf{0hbmH8klI)p&pGiRAK561I%t|n9KJqi~<lw+~<<F5Wv)$C#dZ2#SF2zBpwSI5_D}5K{+&*#1}4tx}YB2'
        'INWZwS*z%~YFyZf(wF)pt<Dl`T;S5k?M-wC^Z2xZ@Dta(xE@hQVh3aF>{`CY9AC|sdVdE82c=s1Hl|H%Y(yoZE~kN3<HQw?RwXo3'
        'wb0XeVz)CYcQjb=M2ywAER2|gRJwXkJwobyo4F(uktE#J>uR3FB8eP^4v&$LB34y3|2%FZ&J9$~_J*<UV{ghA@!cSdR4OPFRD@Pz'
        'H?f8Z!x{cRA11cP9TKrd;+c1L8AWd;BNF$-91|HbacfGaR%bFot;^OW%h0B!>E;3f8Y8TT1=8@?;ttb$a1k!4xwO(u-T}HZ)gAec'
        'N-i3v9!pClQjkapnP!SZin-y{Wq1u<hd1C&cnjW!cTyPR#P+a&r9(w^nMF{t_^j3J6)xXTpEvO_*Ood(M5xu`s3dXQw*__&tG>#7'
        'fqFHn_#k8vl_KgYv_c%<I5+UAI<rAtmj{i3AlNeA^~A$++eI&CXi+a=`fI&hTl^-rak|4Sk*-Z9HkRx2z=$6gblWVdW&n^<vwNDb'
        '?T`lP2Vgz1V>=aR-eW@zK6j?DXO5Q!=NL0a_+jyc!)5#Uk%p)8)ibq4covr6`8%)-FCINL^V!r8Yy$S#5rLb7q;MI>WCw1>@X{W<'
        'ybiAnkPj>Hu9_<X)v#(*0c)uc;k}W%8{FBIAgm9S8hi-X(jws#xZdHCbXHF0tRGSbU>F0A4Qb-v=jijhq)c`ppPU!wF$X^=4snvm'
        '%-sXxr9yqAg!Pf}J$!c@8AWs_Cu3meLnfozK|Gp^CktGd1DQ711EOHur0*l(SNP=^0;)Nr6ZgHd;UTws#!h0=0b6YO&lqtwCj`$B'
        '?u`x|yoq$K5LTQWTKKs?ikk~+=86y=qe0(Y1Gy?^T<v9_(Cn++%f~<P_h>%URL@<el0nJNp8ivGI7dS_pE8yF7yOia`I$t1CX4(`'
        'nUlRvla2zJsdyOzm<J64euTU5JNyKH!XM4)a;XG=B||%r2@J0zh`w&FMdx~Nu19pDxNo-a##?Mca~3h2qzl)3PT+H^A~1KaVCYe<'
        'rm~Y9HE8ZGM`vp;;``Hw=5x6Ezr=qwVn{);*jQK4y3(~C1{cgfWWhJkdSfuSVE!!&-bL%~U~s{l2j4^My}{sqb8`#}&EoH)<NjcL'
        'zu5@g`WFQ+NkXCx000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
